version: '3'
services:
  node:
    restart: always
    build: .
    container_name: nodeapp
    ports:
      - 3000:3000
    image: ${REPO}/${APP}:${env.BUILD_NUMBER}
  mongo:
    image: mongo
    container_name: mongodb-container
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
 mongodb:
